Module4 task2
htmlacademy-nodejs/468109-typoteka-3 pull request #12
Opened 2021-06-15 12:55 UTC by VitalyIonov

2021-06-18 09:38 UTC, Krabaton requested changes
В целом неплохо, но файл по тестированию article создал впечатление легкого хаоса. Как бы describe  и нужны чтобы группировать все. Можно сгруппировать по методам HTTP

2021-06-18 09:38 UTC, Krabaton commented on src/service/api/article.e2e.test.js
> +      .put(`/article/cxGQ17`)
Плохо в таких моментах, что мы харкодим параметр `cxGQ17`, а это значение с мок файла.  Потом харкодим `toBe(`Дам погладить котика`)` это же просто `newArticle.title`. И вот такое везде.

2021-06-18 09:38 UTC, Krabaton commented on src/service/api/article.e2e.test.js
> +test(`API refuses to delete non-existent article`, () => {
А где здесь `async/await`?

2021-06-18 09:38 UTC, Krabaton commented on src/service/api/article.e2e.test.js
> +test(`API refuses to create a comment to non-existent article and returns status code 404`, () => {
async/await?

2021-06-18 09:38 UTC, Krabaton commented on src/service/api/category.e2e.test.js
> +  test(`Category names are "Программирование", "Без рамки", "Железо", "IT", "Музыка", "Разное", "Кино", "За жизнь", "Деревья"`,
А мы каждую категорию будем дописывать теперь, если новая появится?  Просто жизнь показывает, что изменяться будет. Не рационально. Лучше тащить с мока и массив кс троке привести и вставить через шаблонную строку, но чтобы это было в одном месте, а не размазано по коду.

2021-06-18 09:38 UTC, Krabaton commented on src/service/middlewares/searchValidator.js
> +const {StatusCodes, ReasonPhrases} = require(`http-status-codes`);
Одобряю

2021-06-19 06:15 UTC, VitalyIonov commented on src/service/api/category.e2e.test.js
> +  test(`Category names are "Программирование", "Без рамки", "Железо", "IT", "Музыка", "Разное", "Кино", "За жизнь", "Деревья"`,
готово

2021-06-19 08:01 UTC, merged